//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardAccount
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string Pin { get; set; }
        public decimal Cash { get; set; }
    }
}
