//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleNetShop.Data.Excel.Xls {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ExcelSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ExcelSettings defaultInstance = ((ExcelSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ExcelSettings())));
        
        public static ExcelSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source={0};Extended Properties=\'Excel 12.0" +
            " xml;HDR=Yes\';")]
        public string ExcelConnectionStringFormat {
            get {
                return ((string)(this["ExcelConnectionStringFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\InitialData\\InitialData.xlsx")]
        public string InitialProductsFileLocation {
            get {
                return ((string)(this["InitialProductsFileLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\InitialData\\SalesReports\\")]
        public string SalesReportsFoldersLocation {
            get {
                return ((string)(this["SalesReportsFoldersLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\DataSources\\salesReports.zip")]
        public string ZipFileResultLocation {
            get {
                return ((string)(this["ZipFileResultLocation"]));
            }
        }
    }
}
