//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleNetShop.Data.Excel.Xlsx {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class XlsxSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static XlsxSettings defaultInstance = ((XlsxSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new XlsxSettings())));
        
        public static XlsxSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../../../../Reports/XlsxReports/")]
        public string SaveDirectory {
            get {
                return ((string)(this["SaveDirectory"]));
            }
        }
    }
}
