//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursLog
    {
        public int WorkHoursLogID { get; set; }
        public string Command { get; set; }
        public Nullable<int> OldWorkHoursID { get; set; }
        public int OldEmployeeID { get; set; }
        public System.DateTime OldReportDate { get; set; }
        public string OldReportTask { get; set; }
        public Nullable<int> OldReportHours { get; set; }
        public string OldComments { get; set; }
        public Nullable<int> NewWorkHoursID { get; set; }
        public int NewEmployeeID { get; set; }
        public System.DateTime NewReportDate { get; set; }
        public string NewReportTask { get; set; }
        public Nullable<int> NewReportHours { get; set; }
        public string NewComments { get; set; }
    }
}
