namespace UsersGroups
{
    public static class DBCreator
    {
        public static string GetCreationString()
        {
            return @"USE [master]
GO
/****** Object:  Database [UsersGroups]    Script Date: 27/08/2014 19:33:26 ******/
CREATE DATABASE [UsersGroups]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UsersGroups', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\UsersGroups.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'UsersGroups_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\UsersGroups_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [UsersGroups] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UsersGroups].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [UsersGroups] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [UsersGroups] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [UsersGroups] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [UsersGroups] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [UsersGroups] SET ARITHABORT OFF 
GO
ALTER DATABASE [UsersGroups] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [UsersGroups] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [UsersGroups] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [UsersGroups] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [UsersGroups] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [UsersGroups] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [UsersGroups] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [UsersGroups] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [UsersGroups] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [UsersGroups] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [UsersGroups] SET  DISABLE_BROKER 
GO
ALTER DATABASE [UsersGroups] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [UsersGroups] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [UsersGroups] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [UsersGroups] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [UsersGroups] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [UsersGroups] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [UsersGroups] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [UsersGroups] SET RECOVERY FULL 
GO
ALTER DATABASE [UsersGroups] SET  MULTI_USER 
GO
ALTER DATABASE [UsersGroups] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [UsersGroups] SET DB_CHAINING OFF 
GO
ALTER DATABASE [UsersGroups] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [UsersGroups] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'UsersGroups', N'ON'
GO
USE [UsersGroups]
GO
/****** Object:  Table [dbo].[Groups]    Script Date: 27/08/2014 19:33:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Groups](
	[GroupId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Groups] PRIMARY KEY CLUSTERED 
(
	[GroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Users]    Script Date: 27/08/2014 19:33:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[UsersGroups]    Script Date: 27/08/2014 19:33:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UsersGroups](
	[UserId] [int] NOT NULL,
	[GroupId] [int] NOT NULL,
 CONSTRAINT [PK_UsersGroups] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[GroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[UsersGroups]  WITH CHECK ADD  CONSTRAINT [FK_UsersGroups_Groups] FOREIGN KEY([GroupId])
REFERENCES [dbo].[Groups] ([GroupId])
GO
ALTER TABLE [dbo].[UsersGroups] CHECK CONSTRAINT [FK_UsersGroups_Groups]
GO
ALTER TABLE [dbo].[UsersGroups]  WITH CHECK ADD  CONSTRAINT [FK_UsersGroups_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[UsersGroups] CHECK CONSTRAINT [FK_UsersGroups_Users]
GO
USE [master]
GO
ALTER DATABASE [UsersGroups] SET  READ_WRITE 
GO
";
        }
    }
}
